version: '3.8'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - worker
      - redis

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/arc-entrypoint.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - .:/usr/src/volumes/redis

volumes:
  postgres_data: